java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.TypeBinding.isLocalType()" because "originalType" is null
Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4202