Adding back some code that got removed somehow.  Specifically,
- catching NoClassDefFoundError when trying to load an AnnotationProcessorFactory from a jar
- setting up the proper parent for class loaders used to instantiate AnnotationProcessorFactory specified via factory path.

DRTs:  jdt/apt (except for currently broken ReadAnnotationTests)