An attempt to fix classpath entries encoding on Windows
On Windows, passing raw paths to URI constructor results in such errors
below:

```
!ENTRY org.eclipse.jdt.core 4 0 2025-06-30 15:11:54.640
!MESSAGE Unexpected internal error
!STACK 0
java.net.URISyntaxException: Illegal character in path at index 10:
file:///C:\workspaces\Test.index
	at java.base/java.net.URI$Parser.fail(URI.java:2995)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3166)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3248)
	at java.base/java.net.URI$Parser.parse(URI.java:3196)
	at java.base/java.net.URI.<init>(URI.java:645)
	at org.eclipse.jdt.internal.core.ClasspathEntry.getLibraryIndexLocation(ClasspathEntry.java:1785)
	at org.eclipse.jdt.internal.core.ClasspathChange.requestIndexing(ClasspathChange.java:552)
	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2124)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:490)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:321)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:311)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:174)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:465)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1593)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2471)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2482)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:821)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3526)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3486)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3542)
	at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.setClasspath(AbstractJavaModelTests.java:3325)
	at org.eclipse.jdt.core.tests.model.JavaIndexTests.testChangeClasspath(JavaIndexTests.java:587)
```

This patch tries to fix regression from commit
bda8ab24c7e1b7ab32703b94e13b23aa1641ec22.

Still open: failure in
`testUseIndexInternalJarAfterRestart(org.eclipse.jdt.core.tests.model.JavaIndexTests)`

Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4124