IllegalStateException: Preference node "org.eclipse.jdt.core" has been removed (fixes #54)
Don't fail the build on IllegalStateException if someone (git/user)
deleted/replaced project settings while build was running. Let retry
once again (would either read updated file or fall back to defaults).

See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/54